# Generated by Django 5.2.1 on 2025-05-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='定数文言')),
                ('category', models.CharField(max_length=100, verbose_name='定数分類')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '定数',
                'verbose_name_plural': '定数',
                'db_table': 'constant_master',
                'ordering': ['category', 'name'],
            },
        ),
    ]
