# Generated by Django 5.2.1 on 2025-05-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("constant_master", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="constant",
            name="category_key",
            field=models.CharField(
                max_length=255, null=True, verbose_name="定数分類キー"
            ),
        ),
        migrations.AddField(
            model_name="constant",
            name="name_key",
            field=models.CharField(max_length=255, null=True, verbose_name="定数キー"),
        ),
    ]
