# Generated by Django 5.2.1 on 2025-05-09 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memo", "0002_tag_memo_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memo",
            name="tags",
        ),
        migrations.AddField(
            model_name="memo",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memos",
                to="memo.tag",
            ),
        ),
    ]
