# Generated by Django 5.2.1 on 2025-05-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("information", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="information",
            name="delete_flg",
            field=models.BooleanField(default=False, verbose_name="削除フラグ"),
        ),
    ]
